# Generated by Django 5.2.1 on 2025-05-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('das_app', '0003_alter_news_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
    ]
