# Generated by Django 5.2.1 on 2025-05-21 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das_app', '0004_remove_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
