# Generated by Django 5.2.1 on 2025-05-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das_app', '0009_blogs_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=models.CharField(blank=True, help_text='Enter comma-separated tags', max_length=255, null=True),
        ),
    ]
