# Generated by Django 5.2.1 on 2025-10-06 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das_app', '0011_subscriber_alter_blogs_options_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#148255', max_length=7)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-created_date'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AddField(
            model_name='blogs',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short description for blog preview', max_length=300),
        ),
        migrations.AddField(
            model_name='blogs',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='blogs',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='blogs',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogs',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='blogs',
            name='read_time',
            field=models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=models.CharField(blank=True, db_index=True, help_text='Enter comma-separated tags', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='das_app.blogcategory'),
        ),
        migrations.AddIndex(
            model_name='blogs',
            index=models.Index(fields=['created_date', 'is_published'], name='das_app_blo_created_eab563_idx'),
        ),
        migrations.AddIndex(
            model_name='blogs',
            index=models.Index(fields=['tags'], name='das_app_blo_tags_a87d34_idx'),
        ),
        migrations.AddIndex(
            model_name='blogs',
            index=models.Index(fields=['featured', 'created_date'], name='das_app_blo_feature_82ec37_idx'),
        ),
    ]
