# Generated by Django 5.2.1 on 2025-10-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das_app', '0012_blogcategory_alter_blogs_options_blogs_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/'),
        ),
    ]
