# Generated by Django 5.2.1 on 2025-10-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das_app', '0013_alter_blogs_image_alter_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-added_date'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Brief description for news preview', max_length=300),
        ),
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('project', 'Project News'), ('general', 'Overall News')], db_index=True, default='general', max_length=20),
        ),
    ]
