# Generated by Django 5.2.1 on 2025-10-11 05:58

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    News = apps.get_model('das_app', 'News')
    for index, news in enumerate(News.objects.all(), start=1):
        if news.title:
            base_slug = slugify(news.title)
            news.slug = f'{base_slug}-{index}'
        else:
            news.slug = f'news-{index}'
        news.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('das_app', '0014_alter_news_options_news_excerpt_news_news_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, help_text='Full news content', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, default='temp'),
            preserve_default=False,
        ),
        migrations.RunPython(generate_slugs, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(unique=True, blank=True),
        ),
    ]
