# Generated by Django 5.2.1 on 2025-10-11 06:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('das_app', '0015_news_content_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Full blog content with rich text formatting', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Full news content with rich text formatting', null=True),
        ),
    ]
