# Generated by Django 5.2.1 on 2025-10-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das_app', '0016_alter_blogs_content_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Das and Partners Daily'), ('weekly', 'Weekly Updates'), ('monthly', 'Monthly Reports')], db_index=True, default='daily', help_text='Publication frequency', max_length=20),
        ),
    ]
